name: api_client
description: Client to access the api.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
