include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  errors:
    must_be_immutable: ignore
  exclude:
    - lib/l10n/*
    - lib/generated/*
linter:
  rules:
    public_member_api_docs: false
