name: authentication_client
description: An Authentication Client Interface
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^7.0.0
