name: gallery
description: Gallery project to showcase app_ui
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  # `accessibility_tools` is constrained by `widgetbook`, so we can't use the latest
  # version until `widgetbook` updates or removes its dependency on `accessibility_tools`:
  # https://github.com/widgetbook/widgetbook/issues/1197
  accessibility_tools: ^1.0.0
  app_ui:
    path: ../
  flutter:
    sdk: flutter
  two_dimensional_scrollables: ^0.0.6
  widgetbook: ^3.8.0

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
