name: connectivity_repository
description: Flutter package which manages the connectivity domain.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
