name: firebase_authentication_client
description: Auth client using firebase
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_core_platform_interface: ^5.1.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  plugin_platform_interface: ^2.1.2
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
  
