name: fake_app_config_repository
description: A fake implementation of `package:app_config_repository`.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  app_config_repository:
    path: ../app_config_repository

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
