name: fake_app_config_repository_example
description: An example usage of `package:fake_app_config_repository`.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  fake_app_config_repository:
    path: ../

dev_dependencies:
  test: ^1.25.2
