name: "analytics_repository"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/analytics_repository/analytics_repository/**"
      - ".github/workflows/analytics_repository.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: "3.22.0"
      working_directory: '"packages/analytics_repository/analytics_repository"'
      coverage_excludes: "**/*.g.dart"
