name: "app_config_repository"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/app_config_repository/app_config_repository/**"
      - ".github/workflows/app_config_repository.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: "3.22.0"
      working_directory: '"packages/app_config_repository/app_config_repository"'
      coverage_excludes: "**/*.g.dart"
