name: "fake_app_config_repository_example"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/app_config_repository/fake_app_config_repository/example/**"
      - ".github/workflows/fake_app_config_repository_example.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: "packages/app_config_repository/fake_app_config_repository/example"
